trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
# - stage: test
#   displayName: 'Test'
#   jobs:
#   - job: Test
#     steps:
#     - script: |
#         npm install
#         npm test -- --watchAll=false
#       workingDirectory: app
#       displayName: 'run tests'

- stage: build_and_push
  displayName: 'Build and push image to container registry'
  jobs:
  - job: BuildAndPushToRegistry
    steps:
    - task: Docker@2
      displayName: login to docker hub
      inputs:
        command: login
        containerRegistry: docker-hub

    - script: |
        docker-compose build azure-devops-yaml-demo
        docker-compose push azure-devops-yaml-demo
      env:
        DOCKER_IMAGE_TAG: $(Build.SourceBranchName)
      workingDirectory: docker
      displayName: 'docker build and push to registry'

- stage: deploy
  displayName: 'Deploy'
  jobs:
  - job: DeployWebApp
    steps:
    - script: ./deploy.sh
      env:
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      workingDirectory: docker
      displayName: 'run deploy script'


