trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    displayName: Build
    jobs:
    - job: Build
      steps:
        - script: |
            npm install
            npm run build
          workingDirectory: app  
          displayName: 'npm install and build'

  - stage: test
    displayName: Test
    jobs:
    - job: Test
      steps:
        - script: |
            npm install
            npm test
          workingDirectory: app
          displayName: 'run tests'