version: '3.7'

services:
  azure-devops-yaml-demo-prod:
    build:
      context: ..
      dockerfile: './docker/Dockerfile'
      target: serve
    container_name: 'azure-devops-yaml-demo'
    image: 'knapkk/azure-devops-yaml-demo'
    ports:
      - '3333:3333'
