version: '3.7'

services:
  azure-devops-yaml-demo:
    build:
      context: ..
      dockerfile: './docker/Dockerfile'
      target: serve
    container_name: 'azure-devops-yaml-demo-container'
    image: 'knapkk/azure-devops-yaml-demo:${DOCKER_IMAGE_TAG}'
    ports:
      - '3333:3333'
